project:
  type: website
  output-dir: docs

website:
  title: "Sketch Engine tutorial"
  navbar:
    left:
      # - href: index.qmd # Home button removed
      #   text: Home
      - href: SkEtut_slides.qmd
        text: Slides

format:
  html:
    theme: cosmo # You can change or keep this theme
    toc: true
    toc-location: right
    # Potentially add other html options here like code-fold, etc.
  # We will add revealjs defaults back later if everything is stable
